### ISSUE TITLE
I'm having some issues with the async storage.

### ISSUE THREAD

**Issue by premdasvm** [ozer/mateMessage#8]
![Screenshot 2020-08-12 at 5 16 04 PM](https://user-images.githubusercontent.com/14838550/90011604-823b2580-dcbf-11ea-8202-6498a52ffee7.png)

**Comment by premdasvm** [comment]
Add asyncStorage from `import AsyncStorage from '@react-native-community/async-storage';`

**Comment by ozer** [comment]
Hey mate! I'm glad you sorted it out. Please let me know if you have any other issues. I haven't been looking at this project lately so, I am not super sure it works if you update all the dependencies. I can say I recorded and uploaded the video with the latest commit.

**Comment by premdasvm** [comment]
Actually, if it's not a problem, is there anyway i can get in contact
with you? I've just started out on react-native. And would really helpful
to get painters from someone like you.
